// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic/atomic_proto/user/user.proto

package user

import (
	common "atomic/atomic_proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// userId 唯一标识
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 别名
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// 密码
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	// 基本返回信息
	Res *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	// 用户token
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	// 用户名 长度必须大于7位小于13位
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码 长度必须大于7位小于13位
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 别名 长度必须大于8位小于13位
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 手机号码或者电话号码
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type RegisterResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
}

func init() {
	proto.RegisterFile("atomic/atomic_proto/user/user.proto", fileDescriptor_604476ffdad030e1)
}

var fileDescriptor_604476ffdad030e1 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x18, 0x54, 0xd2, 0x74, 0xc9, 0x7a, 0x77, 0x61, 0x65, 0x7e, 0x14, 0xe5, 0x00, 0x55, 0xa8, 0x44,
	0x2f, 0x4d, 0xaa, 0x54, 0x42, 0xe2, 0x86, 0x7a, 0x43, 0xe2, 0x14, 0xc4, 0xa5, 0x17, 0x94, 0x26,
	0x1f, 0xc1, 0x6a, 0x93, 0x2f, 0xd8, 0x6e, 0x8b, 0x78, 0x10, 0xde, 0x85, 0xa7, 0x41, 0xe2, 0x49,
	0x90, 0x7f, 0x12, 0xd2, 0x0a, 0x04, 0x97, 0xbd, 0xd4, 0x9e, 0xf9, 0xc6, 0xe3, 0xe9, 0xd4, 0x25,
	0xcf, 0x73, 0x89, 0x35, 0x2b, 0x12, 0xb3, 0x7c, 0x68, 0x39, 0x4a, 0x4c, 0xf6, 0x02, 0xb8, 0xfe,
	0x88, 0x35, 0xa6, 0x9e, 0xda, 0x87, 0x93, 0x0a, 0xb1, 0xda, 0x41, 0xa2, 0xb9, 0xcd, 0xfe, 0x63,
	0x52, 0x82, 0x28, 0x38, 0x6b, 0x25, 0x5a, 0x5d, 0x98, 0xd6, 0x47, 0x26, 0xb7, 0x78, 0x4c, 0x2a,
	0x9c, 0x6b, 0x66, 0x7e, 0xc8, 0x77, 0xac, 0xcc, 0x25, 0x72, 0xf1, 0xfa, 0xb0, 0x88, 0x97, 0x71,
	0x9a, 0xf4, 0x8c, 0x3d, 0xf3, 0xe2, 0x4f, 0x01, 0x0a, 0xac, 0x6b, 0x6c, 0xec, 0x62, 0x84, 0xd1,
	0x37, 0x87, 0x78, 0xef, 0x05, 0x70, 0x7a, 0x9f, 0xb8, 0xac, 0x0c, 0x9c, 0x89, 0x33, 0x1b, 0x65,
	0x2e, 0x2b, 0x69, 0x48, 0x7c, 0x95, 0xaf, 0xc9, 0x6b, 0x08, 0xdc, 0x89, 0x33, 0xbb, 0xcc, 0x7a,
	0xac, 0x66, 0x0d, 0x2b, 0xb6, 0x7a, 0x36, 0x32, 0xb3, 0x0e, 0xd3, 0x47, 0x64, 0x0c, 0x75, 0xce,
	0x76, 0x81, 0xa7, 0x07, 0x06, 0x28, 0xb6, 0xfd, 0x84, 0x0d, 0x04, 0x63, 0xc3, 0x6a, 0xa0, 0x7c,
	0xda, 0x5c, 0x88, 0x23, 0xf2, 0x32, 0xb8, 0x30, 0x3e, 0x1d, 0x8e, 0xd6, 0xe4, 0xfa, 0x2d, 0x56,
	0xac, 0xc9, 0xe0, 0xf3, 0x1e, 0x84, 0xa4, 0xd3, 0x41, 0x1e, 0x95, 0xf2, 0x72, 0xe5, 0xff, 0xfc,
	0xf1, 0xcc, 0x6b, 0xef, 0x7d, 0xb9, 0x19, 0x24, 0x9b, 0x0e, 0x1c, 0xdd, 0x73, 0x55, 0xef, 0xfd,
	0x86, 0xdc, 0x58, 0x6f, 0xd1, 0x62, 0x23, 0x80, 0x46, 0x64, 0xc4, 0x41, 0x68, 0xdf, 0xab, 0xf4,
	0x36, 0xb6, 0x0d, 0x75, 0xe3, 0x4c, 0x0d, 0xd5, 0x57, 0x90, 0xb8, 0x85, 0xc6, 0xb6, 0x61, 0x40,
	0xf4, 0xdd, 0x21, 0x0f, 0x32, 0xa8, 0x98, 0x90, 0xc0, 0xef, 0x20, 0xaa, 0x52, 0x9d, 0x56, 0x6d,
	0x55, 0xbe, 0x52, 0xfd, 0xa3, 0xf4, 0xa7, 0x27, 0xa5, 0xf7, 0xf6, 0xd7, 0xb6, 0xfe, 0xe8, 0x25,
	0xb9, 0xfd, 0x1d, 0xfd, 0xff, 0x9b, 0x48, 0xbf, 0x92, 0x2b, 0xf5, 0x64, 0xde, 0x01, 0x3f, 0xb0,
	0x02, 0xe8, 0x82, 0x8c, 0x75, 0x9b, 0x94, 0xc6, 0xfa, 0x75, 0x0f, 0x7f, 0xb6, 0xf0, 0xe1, 0x09,
	0x67, 0x2f, 0x79, 0x45, 0xfc, 0xee, 0x62, 0xfa, 0xd8, 0x08, 0xce, 0x3a, 0x0c, 0x9f, 0x9c, 0xd3,
	0xe6, 0xe8, 0x2a, 0x5c, 0x07, 0x7f, 0xfb, 0x6f, 0x6d, 0x2e, 0xf4, 0x7e, 0xf9, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0x88, 0x58, 0xee, 0x41, 0x7e, 0x03, 0x00, 0x00,
}
