// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic/atomic_proto/user/user.proto

package user

import (
	common "atomic/atomic_proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	// 离线
	Status_offline Status = 0
	// 在线
	Status_online Status = 1
	// 被禁用
	Status_disabled Status = 2
)

var Status_name = map[int32]string{
	0: "offline",
	1: "online",
	2: "disabled",
}

var Status_value = map[string]int32{
	"offline":  0,
	"online":   1,
	"disabled": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{0}
}

type User struct {
	// userId 唯一标识
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 别名
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// 密码
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	// 用户名
	// @inject_tag: validate:"required"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" validate:"required"`
	// 密码
	// @inject_tag: validate:"required"
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	// 基本返回信息
	Res *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	// 用户token
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	// 用户名 长度必须大于7位小于13位
	// @inject_tag: validate:"required"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" validate:"required"`
	// 密码 长度必须大于7位小于13位
	// @inject_tag: validate:"required"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	//别名 长度必须大于8位小于13位
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty" validate:"required"`
	// 邮箱
	// @inject_tag: validate:"required,email"
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty" validate:"required,email"`
	// 手机号码或者电话号码
	// @inject_tag: validate:"required"
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type RegisterResponse struct {
	// 基本返回信息
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

type UpdateRequest struct {
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 别名
	// @inject_tag: validate:"required"
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty" validate:"required"`
	// 邮箱
	// @inject_tag: validate:"required,email"
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" validate:"required,email"`
	// 手机或者电话
	// @inject_tag: validate:"required"
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty" validate:"required"`
	// 密码
	// @inject_tag: validate:"required"
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateResponse struct {
	// 基本返回信息
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

type LogoutRequest struct {
	// 用户唯一标识
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{7}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogoutRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LogoutResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_604476ffdad030e1, []int{8}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.Status", Status_name, Status_value)
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "user.UpdateResponse")
	proto.RegisterType((*LogoutRequest)(nil), "user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "user.LogoutResponse")
}

func init() {
	proto.RegisterFile("atomic/atomic_proto/user/user.proto", fileDescriptor_604476ffdad030e1)
}

var fileDescriptor_604476ffdad030e1 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x69, 0x1b, 0xca, 0x74, 0x77, 0xa9, 0xcc, 0x82, 0xa2, 0x9c, 0xaa, 0x70, 0x60, 0xc5,
	0xa1, 0x41, 0xbb, 0x08, 0x09, 0x71, 0xe3, 0x80, 0x84, 0xc4, 0x29, 0xab, 0xbd, 0x70, 0x41, 0x69,
	0x32, 0x2d, 0xd6, 0x36, 0x9e, 0x10, 0x3b, 0xf0, 0x18, 0x88, 0x0b, 0x4f, 0xc8, 0x83, 0x20, 0xdb,
	0x71, 0x4b, 0xca, 0x56, 0x6a, 0x05, 0x97, 0xd8, 0xdf, 0x8c, 0xe7, 0xf3, 0x37, 0x3f, 0x0e, 0x3c,
	0xcd, 0x35, 0x55, 0xa2, 0x48, 0xdd, 0xf2, 0xa9, 0x6e, 0x48, 0x53, 0xda, 0x2a, 0x6c, 0xec, 0x67,
	0x6e, 0x31, 0x1f, 0x9a, 0x7d, 0x3c, 0x5b, 0x11, 0xad, 0xd6, 0x98, 0x5a, 0xdb, 0xa2, 0x5d, 0xa6,
	0x25, 0xaa, 0xa2, 0x11, 0xb5, 0xa6, 0xee, 0x5c, 0xfc, 0xec, 0x2e, 0xb2, 0x82, 0xaa, 0x8a, 0x64,
	0xb7, 0xb8, 0x83, 0xc9, 0x4f, 0x06, 0xc3, 0x1b, 0x85, 0x0d, 0x3f, 0x83, 0x40, 0x94, 0x11, 0x9b,
	0xb1, 0x8b, 0x41, 0x16, 0x88, 0x92, 0xc7, 0x30, 0x36, 0x77, 0xc9, 0xbc, 0xc2, 0x28, 0x98, 0xb1,
	0x8b, 0x07, 0xd9, 0x06, 0x1b, 0x9f, 0x14, 0xc5, 0xad, 0xf5, 0x0d, 0x9c, 0xcf, 0x63, 0x7e, 0x0e,
	0x23, 0xac, 0x72, 0xb1, 0x8e, 0x86, 0xd6, 0xe1, 0x80, 0xb1, 0xd6, 0x9f, 0x49, 0x62, 0x34, 0x72,
	0x56, 0x0b, 0x0c, 0x4f, 0x9d, 0x2b, 0xf5, 0x8d, 0x9a, 0x32, 0x0a, 0x1d, 0x8f, 0xc7, 0xc9, 0x3b,
	0x38, 0xf9, 0x40, 0x2b, 0x21, 0x33, 0xfc, 0xd2, 0xa2, 0xd2, 0x3d, 0x3d, 0xec, 0x6f, 0x3d, 0x1b,
	0x9e, 0x60, 0x87, 0xe7, 0x3d, 0x9c, 0x76, 0x3c, 0xaa, 0x26, 0xa9, 0x90, 0x27, 0x30, 0x68, 0x50,
	0x59, 0x8e, 0xc9, 0xe5, 0x74, 0xde, 0x55, 0xc3, 0xbb, 0x33, 0xe3, 0x34, 0x72, 0x35, 0xdd, 0xa2,
	0xec, 0xd8, 0x1c, 0x48, 0x7e, 0x30, 0x78, 0x98, 0xe1, 0x4a, 0x28, 0x8d, 0xcd, 0x3f, 0xca, 0xfa,
	0x5f, 0x25, 0x4c, 0x5e, 0xc1, 0x74, 0x2b, 0xe9, 0xf0, 0x0c, 0x93, 0xef, 0x0c, 0x4e, 0x6f, 0xea,
	0x32, 0xd7, 0x78, 0x60, 0x26, 0x1b, 0xb5, 0xc1, 0x3e, 0xb5, 0x83, 0x3b, 0xd5, 0x0e, 0xf7, 0x35,
	0x7c, 0xb4, 0xd3, 0xa8, 0x97, 0x70, 0xe6, 0x05, 0x1d, 0x91, 0xc7, 0x1b, 0xdb, 0x5e, 0x6a, 0xb5,
	0x4f, 0xe3, 0x88, 0x39, 0x36, 0x57, 0xfa, 0xe0, 0xc3, 0xaf, 0x7c, 0x9e, 0x42, 0x78, 0xad, 0x73,
	0xdd, 0x2a, 0x3e, 0x81, 0xfb, 0xb4, 0x5c, 0xae, 0x85, 0xc4, 0xe9, 0x3d, 0x0e, 0x10, 0x92, 0xb4,
	0x7b, 0xc6, 0x4f, 0x60, 0x5c, 0x0a, 0x95, 0x2f, 0xd6, 0x58, 0x4e, 0x83, 0xcb, 0x5f, 0x0c, 0x26,
	0xe6, 0x8d, 0x5d, 0x63, 0xf3, 0x55, 0x14, 0xc8, 0x5f, 0xc0, 0xc8, 0x8e, 0x24, 0xe7, 0x73, 0xfb,
	0xb4, 0xff, 0x9c, 0xf3, 0xf8, 0x51, 0xcf, 0xd6, 0xc9, 0x7a, 0x0d, 0x63, 0xdf, 0x65, 0xfe, 0xd8,
	0x1d, 0xd8, 0x19, 0xc4, 0xf8, 0xc9, 0xae, 0xb9, 0x0b, 0xbd, 0x82, 0xd0, 0x95, 0x95, 0x77, 0xcc,
	0xbd, 0xae, 0xc7, 0xe7, 0x7d, 0xe3, 0x36, 0xc8, 0x15, 0x86, 0x6f, 0xe5, 0x6c, 0x6b, 0xec, 0x83,
	0xfa, 0xb5, 0x7b, 0x1b, 0x7f, 0x8c, 0xf6, 0xfd, 0xc2, 0x16, 0xa1, 0xdd, 0x5f, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x99, 0xc7, 0xe3, 0xe5, 0x04, 0x00, 0x00,
}
