// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic/atomic_server/proto/user/user.proto

package user

import (
	common "atomic/atomic_server/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// userId 唯一标识
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 别名
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// 密码
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a55e33fc7448741a, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a55e33fc7448741a, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a55e33fc7448741a, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a55e33fc7448741a, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type RegisterResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a55e33fc7448741a, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
}

func init() {
	proto.RegisterFile("atomic/atomic_server/proto/user/user.proto", fileDescriptor_a55e33fc7448741a)
}

var fileDescriptor_a55e33fc7448741a = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0xae, 0x9a, 0x40,
	0x18, 0x0d, 0x88, 0x16, 0x47, 0xdb, 0x9a, 0xb1, 0x6d, 0x08, 0x8b, 0x6a, 0x89, 0x0b, 0xd3, 0x44,
	0x30, 0x98, 0x34, 0xe9, 0xae, 0x71, 0xdd, 0x15, 0x4d, 0x37, 0x6e, 0x1a, 0x84, 0xaf, 0x74, 0xa2,
	0x30, 0x74, 0x06, 0xd1, 0xf4, 0x41, 0xfa, 0x2e, 0xf7, 0x69, 0x6e, 0x72, 0x9f, 0xe4, 0x66, 0x7e,
	0xf0, 0xa2, 0x1b, 0xef, 0xe6, 0x6e, 0x98, 0xf9, 0xce, 0x77, 0xbe, 0x33, 0x87, 0xc3, 0x80, 0x3e,
	0xc7, 0x15, 0xcd, 0x49, 0x12, 0xa8, 0xe5, 0x17, 0x07, 0x56, 0x03, 0x0b, 0x4a, 0x46, 0x2b, 0x1a,
	0x1c, 0x38, 0x30, 0xf9, 0xf0, 0x65, 0x8d, 0x2d, 0xb1, 0x77, 0xa7, 0x19, 0xa5, 0xd9, 0x1e, 0x14,
	0x67, 0x7b, 0xf8, 0x1d, 0xa4, 0xc0, 0x13, 0x46, 0xca, 0x8a, 0x6a, 0x9e, 0x1b, 0xe6, 0x47, 0x52,
	0xed, 0xe8, 0x31, 0xc8, 0xe8, 0x42, 0x22, 0x8b, 0x3a, 0xde, 0x93, 0x34, 0xae, 0x28, 0xe3, 0xdf,
	0xea, 0xa5, 0xbf, 0xf2, 0xc3, 0xe0, 0x8c, 0xe8, 0x99, 0x71, 0x42, 0xf3, 0x9c, 0x16, 0x81, 0x5a,
	0x14, 0xe8, 0xfd, 0x37, 0x90, 0xf5, 0x93, 0x03, 0xc3, 0x6f, 0x90, 0x49, 0x52, 0xc7, 0x98, 0x1a,
	0xf3, 0x4e, 0x64, 0x92, 0x14, 0xbb, 0xc8, 0x16, 0x5e, 0x8a, 0x38, 0x07, 0xc7, 0x9c, 0x1a, 0xf3,
	0x7e, 0x74, 0xae, 0x45, 0xaf, 0x20, 0xc9, 0x4e, 0xf6, 0x3a, 0xaa, 0xd7, 0xd4, 0xf8, 0x1d, 0xea,
	0x42, 0x1e, 0x93, 0xbd, 0x63, 0xc9, 0x86, 0x2a, 0x04, 0x5a, 0xfe, 0xa1, 0x05, 0x38, 0x5d, 0x85,
	0xca, 0x42, 0xe8, 0x94, 0x31, 0xe7, 0x47, 0xca, 0x52, 0xa7, 0xa7, 0x74, 0x9a, 0xda, 0xdb, 0xa0,
	0xe1, 0x77, 0x9a, 0x91, 0x22, 0x82, 0xbf, 0x07, 0xe0, 0x15, 0x9e, 0xb5, 0xfc, 0x08, 0x97, 0xfd,
	0xb5, 0xfd, 0x70, 0x3f, 0xb1, 0xca, 0xde, 0x69, 0xd8, 0x72, 0x36, 0x6b, 0x29, 0x9a, 0xd7, 0xac,
	0xb3, 0xf6, 0x0a, 0xbd, 0xd6, 0xda, 0xbc, 0xa4, 0x05, 0x07, 0xec, 0xa1, 0x0e, 0x03, 0x2e, 0x75,
	0x07, 0xe1, 0xc8, 0xd7, 0x09, 0x35, 0xed, 0x48, 0x34, 0xbd, 0x3b, 0x03, 0xbd, 0x8d, 0x20, 0x23,
	0xbc, 0x02, 0xf6, 0x02, 0xa6, 0x04, 0xeb, 0x32, 0x54, 0xcd, 0xb2, 0x05, 0xeb, 0x46, 0xbc, 0x1f,
	0x2f, 0xe2, 0xd5, 0x83, 0xaf, 0x4e, 0x43, 0x1d, 0xb4, 0xf7, 0x05, 0x8d, 0x9e, 0xac, 0x3f, 0xff,
	0x9d, 0xc3, 0x7f, 0x68, 0x20, 0x2e, 0xc7, 0x0f, 0x60, 0x35, 0x49, 0x00, 0x2f, 0x51, 0x57, 0xe6,
	0x86, 0xb1, 0x2f, 0xef, 0x6c, 0xfb, 0x03, 0xb9, 0xe3, 0x0b, 0x4c, 0x1f, 0xf2, 0x15, 0xd9, 0xcd,
	0xc1, 0xf8, 0xbd, 0x22, 0x5c, 0x65, 0xe8, 0x7e, 0xb8, 0x86, 0xd5, 0xe8, 0xfa, 0xd3, 0x66, 0x72,
	0xe3, 0xc7, 0xd9, 0xf6, 0xe4, 0x7e, 0xf5, 0x18, 0x00, 0x00, 0xff, 0xff, 0x56, 0x5e, 0xcc, 0xc2,
	0x62, 0x03, 0x00, 0x00,
}
