// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atomic/atomic_server/proto/user/user.proto

package user

import (
	_ "atomic/atomic_server/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *LoginRequest) Validate() error {
	if !(len(this.Username) > 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length greater than '6'`, this.Username))
	}
	if !(len(this.Username) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Username))
	}
	if !(len(this.Password) > 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length greater than '6'`, this.Password))
	}
	if !(len(this.Password) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Password))
	}
	return nil
}
func (this *LoginResponse) Validate() error {
	if this.Res != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Res); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Res", err)
		}
	}
	return nil
}
func (this *RegisterRequest) Validate() error {
	if !(len(this.Username) > 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length greater than '6'`, this.Username))
	}
	if !(len(this.Username) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Username))
	}
	if !(len(this.Password) > 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length greater than '6'`, this.Password))
	}
	if !(len(this.Password) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Password))
	}
	if !(len(this.Nickname) > 8) {
		return github_com_mwitkow_go_proto_validators.FieldError("Nickname", fmt.Errorf(`value '%v' must have a length greater than '8'`, this.Nickname))
	}
	if !(len(this.Nickname) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Nickname", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Nickname))
	}
	if !(len(this.Phone) > 7) {
		return github_com_mwitkow_go_proto_validators.FieldError("Phone", fmt.Errorf(`value '%v' must have a length greater than '7'`, this.Phone))
	}
	if !(len(this.Phone) < 12) {
		return github_com_mwitkow_go_proto_validators.FieldError("Phone", fmt.Errorf(`value '%v' must have a length smaller than '12'`, this.Phone))
	}
	return nil
}
func (this *RegisterResponse) Validate() error {
	if this.Res != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Res); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Res", err)
		}
	}
	return nil
}
