// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic_server/proto/user/user.proto

package user

import (
	common "atomic/atomic_server/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// userId 唯一标识
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 别名
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// 密码
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebd0a679eab2930b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebd0a679eab2930b, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebd0a679eab2930b, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
}

func init() {
	proto.RegisterFile("atomic_server/proto/user/user.proto", fileDescriptor_ebd0a679eab2930b)
}

var fileDescriptor_ebd0a679eab2930b = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0xfc, 0xa9, 0xe0, 0x0a, 0x08, 0x19, 0x06, 0x2b, 0x0b, 0x25, 0x0c, 0x74, 0x4a,
	0x50, 0xfb, 0x00, 0x48, 0x0c, 0x4c, 0x4c, 0x41, 0x2c, 0x2c, 0x28, 0x24, 0x27, 0xb0, 0xc0, 0x76,
	0xb0, 0xd3, 0xf2, 0x26, 0x3c, 0x2f, 0xf2, 0x39, 0xa9, 0x28, 0xd0, 0xc5, 0xbe, 0xef, 0xbe, 0xd3,
	0x4f, 0xa7, 0xef, 0xe0, 0xa2, 0xee, 0x8d, 0x92, 0xcd, 0x93, 0x43, 0xbb, 0x46, 0x5b, 0x76, 0xd6,
	0xf4, 0xa6, 0x5c, 0x39, 0xb4, 0xf4, 0x14, 0xa4, 0x79, 0xe2, 0xeb, 0xec, 0xf2, 0xbf, 0xd1, 0xc6,
	0x28, 0x65, 0xf4, 0xf0, 0x85, 0xf1, 0xfc, 0x8b, 0x41, 0xf2, 0xe0, 0xd0, 0xf2, 0x23, 0x88, 0x64,
	0x2b, 0xd8, 0x8c, 0xcd, 0xe3, 0x2a, 0x92, 0x2d, 0xcf, 0x60, 0xcf, 0x93, 0x74, 0xad, 0x50, 0x44,
	0x33, 0x36, 0xdf, 0xaf, 0x36, 0xda, 0x7b, 0x5a, 0x36, 0x6f, 0xe4, 0xc5, 0xc1, 0x1b, 0x35, 0x3f,
	0x85, 0x14, 0x55, 0x2d, 0xdf, 0x45, 0x42, 0x46, 0x10, 0xbe, 0xdb, 0xbd, 0x1a, 0x8d, 0x22, 0x0d,
	0x5d, 0x12, 0x9e, 0xd3, 0xd5, 0xce, 0x7d, 0x1a, 0xdb, 0x8a, 0x49, 0xe0, 0x8c, 0x3a, 0xbf, 0x85,
	0x83, 0x3b, 0xf3, 0x22, 0x75, 0x85, 0x1f, 0x2b, 0x74, 0xfd, 0xd6, 0x3e, 0xec, 0xef, 0x3e, 0x1b,
	0x4e, 0xf4, 0x8b, 0xb3, 0x84, 0xc3, 0x81, 0xe3, 0x3a, 0xa3, 0x1d, 0xf2, 0x1c, 0x62, 0x8b, 0x8e,
	0x18, 0xd3, 0xc5, 0x71, 0x31, 0xa4, 0x31, 0xda, 0x95, 0x37, 0x17, 0xd7, 0x30, 0xf5, 0xa1, 0xdc,
	0xa3, 0x5d, 0xcb, 0x06, 0xf9, 0x15, 0xa4, 0xc4, 0xe0, 0xbc, 0xa0, 0xa4, 0x7f, 0x2e, 0x96, 0x9d,
	0x6c, 0xf5, 0x02, 0xe5, 0xe6, 0xfc, 0xf1, 0x2c, 0x5c, 0xa0, 0xdc, 0x75, 0xb3, 0xe7, 0x09, 0xd5,
	0xcb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xc0, 0x12, 0xb2, 0xd6, 0x01, 0x00, 0x00,
}
