// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic/atomic_proto/blog/blog.proto

package blog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonBlog struct {
	// 唯一标识符
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 博客标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 文章内容
	Content []string `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	// 属于某个用户
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonBlog) Reset()         { *m = CommonBlog{} }
func (m *CommonBlog) String() string { return proto.CompactTextString(m) }
func (*CommonBlog) ProtoMessage()    {}
func (*CommonBlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{0}
}

func (m *CommonBlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonBlog.Unmarshal(m, b)
}
func (m *CommonBlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonBlog.Marshal(b, m, deterministic)
}
func (m *CommonBlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonBlog.Merge(m, src)
}
func (m *CommonBlog) XXX_Size() int {
	return xxx_messageInfo_CommonBlog.Size(m)
}
func (m *CommonBlog) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonBlog.DiscardUnknown(m)
}

var xxx_messageInfo_CommonBlog proto.InternalMessageInfo

func (m *CommonBlog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommonBlog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CommonBlog) GetContent() []string {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CommonBlog) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonBlog)(nil), "blog.CommonBlog")
}

func init() {
	proto.RegisterFile("atomic/atomic_proto/blog/blog.proto", fileDescriptor_92db37cf00cb4a6f)
}

var fileDescriptor_92db37cf00cb4a6f = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0x2c, 0xc9, 0xcf,
	0xcd, 0x4c, 0xd6, 0x87, 0x50, 0xf1, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0xfa, 0x49, 0x39, 0xf9, 0xe9,
	0x60, 0x42, 0x0f, 0xcc, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x32, 0xb8, 0xb8, 0x9c, 0xf3, 0x73, 0x73,
	0xf3, 0xf3, 0x9c, 0x72, 0xf2, 0xd3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92,
	0xd4, 0xbc, 0x12, 0x09, 0x66, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0xa3,
	0xb4, 0x38, 0xb5, 0x28, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x05, 0xac, 0x05, 0xce, 0x37, 0xe2, 0xe5,
	0xe2, 0x06, 0xd9, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x9a, 0xc4, 0x06, 0x76, 0x85, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x43, 0x6f, 0x36, 0xac, 0x00, 0x00, 0x00,
}
