// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: atomic/atomic_proto/blog/blog.proto

package blog

import (
	_ "atomic/atomic_proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommonBlogService service

type CommonBlogService interface {
	// 创建
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	// 删除
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type commonBlogService struct {
	c    client.Client
	name string
}

func NewCommonBlogService(name string, c client.Client) CommonBlogService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "blog"
	}
	return &commonBlogService{
		c:    c,
		name: name,
	}
}

func (c *commonBlogService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.name, "CommonBlogService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonBlogService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "CommonBlogService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommonBlogService service

type CommonBlogServiceHandler interface {
	// 创建
	Create(context.Context, *CreateRequest, *CreateResponse) error
	// 删除
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterCommonBlogServiceHandler(s server.Server, hdlr CommonBlogServiceHandler, opts ...server.HandlerOption) error {
	type commonBlogService interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type CommonBlogService struct {
		commonBlogService
	}
	h := &commonBlogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CommonBlogService{h}, opts...))
}

type commonBlogServiceHandler struct {
	CommonBlogServiceHandler
}

func (h *commonBlogServiceHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.CommonBlogServiceHandler.Create(ctx, in, out)
}

func (h *commonBlogServiceHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.CommonBlogServiceHandler.Delete(ctx, in, out)
}
