// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atomic/atomic_proto/blog/blog.proto

package blog

import (
	_ "atomic/atomic_proto/common"
	_ "atomic/atomic_proto/user"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CreateBlogRequest) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *CreateBlogResponse) Validate() error {
	if this.Res != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Res); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Res", err)
		}
	}
	return nil
}
