// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic/atomic_proto/blog/blog.proto

package blog

import (
	common "atomic/atomic_proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	// 标题 6到10个字之内
	// @inject_tag: validate:"required,max=11,min=8"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 文章内容
	// @inject_tag: validate:"required"
	Content []string `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	// 用户唯一标识
	// @inject_tag: validate:"required,max=12,min=7"
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetContent() []string {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateResponse struct {
	// 基本返回信息
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

type CommonBlog struct {
	// 唯一标识符
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 博客标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 文章内容
	Content []string `protobuf:"bytes,3,rep,name=content,proto3" json:"content,omitempty"`
	// 属于某个用户
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonBlog) Reset()         { *m = CommonBlog{} }
func (m *CommonBlog) String() string { return proto.CompactTextString(m) }
func (*CommonBlog) ProtoMessage()    {}
func (*CommonBlog) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{2}
}

func (m *CommonBlog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonBlog.Unmarshal(m, b)
}
func (m *CommonBlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonBlog.Marshal(b, m, deterministic)
}
func (m *CommonBlog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonBlog.Merge(m, src)
}
func (m *CommonBlog) XXX_Size() int {
	return xxx_messageInfo_CommonBlog.Size(m)
}
func (m *CommonBlog) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonBlog.DiscardUnknown(m)
}

var xxx_messageInfo_CommonBlog proto.InternalMessageInfo

func (m *CommonBlog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommonBlog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CommonBlog) GetContent() []string {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CommonBlog) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DeleteRequest struct {
	// 用户名
	// @inject_tag: validate:"required,max=12,min=7"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 博客唯一标识
	// @inject_tag: validate:"required"
	BlogId               int64    `protobuf:"varint,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DeleteRequest) GetBlogId() int64 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

type DeleteResponse struct {
	// 基本返回信息
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db37cf00cb4a6f, []int{4}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "blog.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "blog.CreateResponse")
	proto.RegisterType((*CommonBlog)(nil), "blog.CommonBlog")
	proto.RegisterType((*DeleteRequest)(nil), "blog.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "blog.DeleteResponse")
}

func init() {
	proto.RegisterFile("atomic/atomic_proto/blog/blog.proto", fileDescriptor_92db37cf00cb4a6f)
}

var fileDescriptor_92db37cf00cb4a6f = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0x0e, 0x2b, 0x0e, 0x79, 0x04, 0x62, 0x2a, 0x89, 0xcb, 0x4e, 0x64, 0x1e, 0xe4, 0x34, 0x12,
	0xe6, 0x2f, 0x10, 0x2e, 0x5e, 0xeb, 0xd1, 0x03, 0x19, 0xdb, 0x0b, 0x36, 0xd9, 0x56, 0x6c, 0x8b,
	0xfe, 0x7d, 0xd3, 0x76, 0x15, 0x6b, 0x24, 0xf1, 0xb2, 0xee, 0x6b, 0xbf, 0xef, 0xbd, 0xef, 0x7b,
	0x0f, 0xee, 0x4b, 0x2d, 0x5a, 0x5e, 0xad, 0xdc, 0xb1, 0x3b, 0x4a, 0xa1, 0xc5, 0x6a, 0xdf, 0x88,
	0x83, 0xfd, 0xe4, 0x16, 0xd3, 0xa1, 0xf9, 0x4f, 0x1f, 0xfe, 0xa2, 0x56, 0xa2, 0x6d, 0x45, 0xd7,
	0x1f, 0x8e, 0x9e, 0xbd, 0xc2, 0x74, 0x23, 0xb1, 0xd4, 0xc8, 0xf0, 0xfd, 0x84, 0x4a, 0xd3, 0x39,
	0x5c, 0x69, 0xae, 0x1b, 0x4c, 0x06, 0x8b, 0xc1, 0x72, 0xcc, 0x1c, 0xa0, 0x09, 0x8c, 0x2a, 0xd1,
	0x69, 0xec, 0x74, 0x12, 0x2d, 0xc8, 0x72, 0xcc, 0x3c, 0xa4, 0x29, 0x5c, 0x9f, 0x14, 0xca, 0xae,
	0x6c, 0x31, 0x21, 0x56, 0xf2, 0x8d, 0xb3, 0x47, 0x98, 0xf9, 0xe2, 0xea, 0x28, 0x3a, 0x85, 0x34,
	0x03, 0x22, 0x51, 0xd9, 0xda, 0x93, 0xf5, 0x4d, 0xde, 0x5b, 0xf1, 0xcf, 0xcc, 0x3c, 0x66, 0x6f,
	0x00, 0x1b, 0x7b, 0xff, 0xd4, 0x88, 0x03, 0x9d, 0x41, 0xc4, 0x6b, 0x2b, 0x20, 0x2c, 0xe2, 0xf5,
	0xd9, 0x5f, 0x74, 0xc1, 0x1f, 0xb9, 0xec, 0x6f, 0xf8, 0xcb, 0xdf, 0x16, 0xa6, 0x5b, 0x6c, 0xf0,
	0x1c, 0xfe, 0x27, 0x79, 0x10, 0x92, 0xe9, 0x1d, 0x8c, 0xcc, 0x68, 0x77, 0xbc, 0xb6, 0xad, 0x09,
	0x8b, 0x0d, 0x7c, 0xae, 0x4d, 0x4a, 0x5f, 0xe5, 0xff, 0x29, 0xd7, 0x9f, 0x30, 0x31, 0xf9, 0x5e,
	0x50, 0x7e, 0xf0, 0x0a, 0x69, 0x01, 0xb1, 0x1b, 0x15, 0xbd, 0xcd, 0xed, 0x36, 0x83, 0xad, 0xa4,
	0xf3, 0xf0, 0xb2, 0xef, 0x53, 0x40, 0xec, 0x3a, 0x7b, 0x51, 0x90, 0xc6, 0x8b, 0x42, 0x73, 0xfb,
	0xd8, 0x2e, 0xbe, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x25, 0x45, 0x1c, 0x19, 0x4e, 0x02, 0x00,
	0x00,
}
