// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomic_server/proto/blog/blog.proto

package blog

import (
	common "atomic/atomic_server/proto/common"
	user "atomic/atomic_server/proto/user"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBlogRequest struct {
	User                 *user.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Title                string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fde7ce08e658bb1, []int{0}
}

func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(m, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateBlogRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateBlogRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBlogResponse struct {
	Res                  *common.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fde7ce08e658bb1, []int{1}
}

func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (m *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(m, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetRes() *common.Response {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
}

func init() {
	proto.RegisterFile("atomic_server/proto/blog/blog.proto", fileDescriptor_4fde7ce08e658bb1)
}

var fileDescriptor_4fde7ce08e658bb1 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0x03, 0x41,
	0x0c, 0x65, 0x6d, 0xad, 0x98, 0x5e, 0x34, 0x08, 0x0e, 0x7b, 0x90, 0xb2, 0x1e, 0xec, 0x69, 0x0b,
	0xf5, 0x22, 0x78, 0xd3, 0x9b, 0xc7, 0x15, 0xcf, 0xd2, 0x0e, 0xa1, 0x2c, 0xec, 0x4e, 0x6a, 0x26,
	0xed, 0xf7, 0xcb, 0x64, 0xb6, 0x50, 0xe8, 0x5e, 0x32, 0xf3, 0xf2, 0xde, 0xbc, 0xbc, 0x09, 0x3c,
	0x6f, 0x94, 0xfb, 0xd6, 0xff, 0x46, 0x92, 0x23, 0xc9, 0x6a, 0x2f, 0xac, 0xbc, 0xda, 0x76, 0xbc,
	0xb3, 0x52, 0x1b, 0xc6, 0x69, 0xba, 0x97, 0xa3, 0xd2, 0x43, 0x24, 0xb1, 0x92, 0xa5, 0xe5, 0xcb,
	0x98, 0xc8, 0x73, 0xdf, 0x73, 0x18, 0x8e, 0x2c, 0xac, 0x3c, 0xdc, 0x7f, 0x0a, 0x6d, 0x94, 0x3e,
	0x3a, 0xde, 0x35, 0xf4, 0x77, 0xa0, 0xa8, 0xf8, 0x04, 0xd3, 0xe4, 0xe5, 0x8a, 0x45, 0xb1, 0x9c,
	0xaf, 0xa1, 0x36, 0xe3, 0x9f, 0x48, 0xd2, 0x58, 0x1f, 0x1f, 0xe0, 0x5a, 0x5b, 0xed, 0xc8, 0x5d,
	0x2d, 0x8a, 0xe5, 0x6d, 0x93, 0x01, 0x3a, 0xb8, 0xf1, 0x1c, 0x94, 0x82, 0xba, 0x89, 0xf5, 0x4f,
	0xb0, 0x7a, 0x03, 0x3c, 0x1f, 0x12, 0xf7, 0x1c, 0x22, 0x61, 0x05, 0x13, 0xa1, 0x38, 0x0c, 0xb9,
	0xab, 0x87, 0x58, 0x27, 0xba, 0x49, 0xe4, 0xfa, 0x0b, 0xe6, 0xe9, 0xcd, 0x37, 0xc9, 0xb1, 0xf5,
	0x84, 0xef, 0x30, 0xcb, 0x46, 0xf8, 0x58, 0xdb, 0x62, 0x2e, 0xb2, 0x97, 0xee, 0x92, 0xc8, 0x86,
	0xdb, 0x99, 0xfd, 0xf8, 0xf5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x17, 0x6f, 0xbb, 0x6c, 0x01,
	0x00, 0x00,
}
